variable "resource_group_name" { }
variable "location" { }
variable "app_name" { }
variable "env_name" { }
variable "name" { }
variable "subnet_id" { }
variable "admin_username" { }
variable "admin_password" { }
variable "diag_endpoint" { }
variable "log_analytics_workspace_id" { }
variable "log_analytics_workspace_key" { }